source_dir: "/home/sssakana/pond/Pictures_Videos/inbox"
target_dir: "/home/sssakana/pond/Pictures_Videos"
log_path: "/home/sssakana/pond/Pictures_Videos/.logs/file_sorter.log"
geo_cache_path: "/home/sssakana/pond/Pictures_Videos/.runtime_data/geo_cache.json"
thread_count: 0  # 0 means auto-detect based on hardware
copy_only: false  # true for copy, false for move